language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

services:
  - postgresql

env:
  - DJANGO_VERSION=1.11b1
  - DJANGO_VERSION=1.10.5
  - DJANGO_VERSION=1.9.9

install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install requests-mock mock pytest coveralls"

script:
  - env
  - env PYTHONPATH=`pwd` coverage run --source=hordak ./manage.py test hordak

after_success:
  coveralls

addons:
  postgresql: "9.2"
